### ISSUE TITLE
why do the annotations in the "rotate" directory only have horizontal bboxes?

### ISSUE THREAD

**Issue by MingtaoFu** [hitachi-rd-cv/omnidet-rotinv#1]
An object only has xmin, ymin, xmax and ymax and there isn't an "angle" in it.

**Comment by tamtamz** [comment]
As explained in our paper, the angles of the bounding boxes are not explicitly determined, but the angles are determined by the positions of the bounding boxes. The angle for each bounding box is the angle between a vertical line and a line connecting an image center and a bounding box center. Therefore, to get rotated bounding boxes, first you have to calculate its angle and then rotate the bounding box by yourself.
